### ISSUE TITLE
Class name change

### ISSUE THREAD

**Issue by SimStim** [nicolomantini/LinkedIn-Easy-Apply-Bot#100]
**Describe the bug**
Class name has changed

**Screenshots**
Not applicable, it is the list of jobs, the big list on the left side

**Logs**
N/A

**Error Statement**
Traceback (most recent call last):
  File "/run/media/Ed/bcache0/Nextcloud/LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 452, in <module>
    bot.start_apply(positions, locations)
  File "/run/media/Ed/bcache0/Nextcloud/LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 133, in start_apply
    self.applications_loop(position, location)
  File "/run/media/Ed/bcache0/Nextcloud/LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 164, in applications_loop
    scrollresults = self.browser.find_element(By.CLASS_NAME,
  File "/home/Ed/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 857, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/Ed/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/Ed/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".jobs-search-results"}
  (Session info: chrome=104.0.5112.79)
Stacktrace:
#0 0x5628f39b7403 <unknown>
#1 0x5628f37bd778 <unknown>
#2 0x5628f37f4c87 <unknown>
#3 0x5628f37f4e51 <unknown>
#4 0x5628f3827f24 <unknown>
#5 0x5628f3812a2d <unknown>
#6 0x5628f3825c74 <unknown>
#7 0x5628f38128f3 <unknown>
#8 0x5628f37e80d8 <unknown>
#9 0x5628f37e9205 <unknown>
#10 0x5628f39fee3d <unknown>
#11 0x5628f3a01db6 <unknown>
#12 0x5628f39e813e <unknown>
#13 0x5628f3a029b5 <unknown>
#14 0x5628f39dc970 <unknown>
#15 0x5628f3a1f228 <unknown>
#16 0x5628f3a1f3bf <unknown>
#17 0x5628f3a39abe <unknown>
#18 0x7fcd78a8ce2d <unknown>

**Desktop (please complete the following information):**
Fedora 36

**To Reproduce**
python3 easyapplybot.py 
(and then wait for the wake-up)

**Expected behavior**
No crash?

**Additional context**
Fix:
Change line 165:
                "jobs-search-results"
To:
                "jobs-search-results-list"

**Comment by nicolomantini** [comment]
pull request?

**Comment by SimStim** [comment]
Oh, I usually don't do pull-requests for 5 changed characters ;-) But after these changes your script should work again. You could just copy&paste it into your code.
Cheers, Ed
