### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by EdwardOak** [nicolomantini/LinkedIn-Easy-Apply-Bot#110]
Check last replies

**Comment by EdwardOak** [comment]
Reading online about it but it's over my head.

**Comment by EdwardOak** [comment]
I'm on Debian, should I absolutely be on Ubuntu?

**Comment by EdwardOak** [comment]
Additionally, I'm not running from a venv

**Comment by EdwardOak** [comment]
Tried to 
python -m venv test_vm
source test_vm/bin/activate

and run from there, same issue.

**Comment by EdwardOak** [comment]
Anyone? Any leads? 

Pls :/

**Comment by ZaneBaylon** [comment]
Looks like you have an extra ')' on line 22?

**Comment by ZaneBaylon** [comment]
It's definitely something to do with a driver conflict. If you've downloaded a google driver before, or are on a relatively unique OS like you said, it might just not be compatible. Are you running this from any kind of shell?

**Comment by EdwardOak** [comment]
Debian buster, fresh install.

**Comment by EdwardOak** [comment]
Sorry, Debian Bullseye** brainfart

**Comment by EdwardOak** [comment]
> It's definitely something to do with a driver conflict. If you've downloaded a google driver before, or are on a relatively unique OS like you said, it might just not be compatible. Are you running this from any kind of shell?

I'm realizing I'm running from a Chrome Remote Desktop (installed/deployed via startut script)

I'll try again on a local computer.

**Comment by EdwardOak** [comment]
### Ran from a fresh Ubuntu VM, followed instructions, ran from conda env. 
`(myenv) garyoak@garyoak-VirtualBox:~/Desktop/linkedin/LinkedIn-Easy-Apply-Bot-master$ python3 easyapplybot.py 
Traceback (most recent call last):
  File "/home/garyoak/Desktop/linkedin/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 16, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
  File "/home/garyoak/.local/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 7, in <module>
    from webdriver_manager.drivers.chrome import ChromeDriver
  File "/home/garyoak/.local/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 1, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
`

**Comment by EdwardOak** [comment]
Installed "packaging" - now the issue is: 
**.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary**

Yes, selenium is installed (through requirements file)

**Comment by EdwardOak** [comment]
Man this git's documentation is utter garbage. 

I changed line 22 to include the direct path. 

Now this:

`driver = webdriver.Chrome(chrome_options = Options, executable_path=r'/home/garyoak/Desktop/linkedin/LinkedIn-Easy-Apply-Bot-master/assets/chromedriver_linux')
  File "/home/garyoak/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/garyoak/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 82, in __init__
    if options._ignore_local_proxy:
AttributeError: type object 'Options' has no attribute '_ignore_local_proxy'`

**Comment by EdwardOak** [comment]
and if I sudo:

`sudo python3 easyapplybot.py 
[sudo] password for garyoak: 
Traceback (most recent call last):
  File "/home/garyoak/Desktop/linkedin/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 13, in <module>
    import pyautogui
  File "/usr/local/lib/python3.10/dist-packages/pyautogui/__init__.py", line 249, in <module>
    import mouseinfo
  File "/usr/local/lib/python3.10/dist-packages/mouseinfo/__init__.py", line 223, in <module>
    _display = Display(os.environ['DISPLAY'])
  File "/usr/local/lib/python3.10/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.10/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/local/lib/python3.10/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\`
