### ISSUE TITLE
Received this error when starting the program

### ISSUE THREAD

**Issue by dorissssy** [nicolomantini/LinkedIn-Easy-Apply-Bot#168]
10:59:44 - INFO - Welcome to Easy Apply Bot
10:59:44 - INFO - current directory is : /Users/.../LinkedIn-Easy-Apply-Bot
10:59:44 - INFO - 28 jobIDs found
10:59:56 - INFO - Logging in.....Please wait :)  
Traceback (most recent call last):
  File "/Users/.../LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 693, in <module>
    bot = EasyApplyBot(parameters['username'],
  File "/Users/.../LinkedIn-Easy-Apply-Bot/easyapplybot.py", line 115, in __init__
    df = pd.read_csv(self.qa_file)
  File "/Users/.../LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/.../LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/.../LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 488, in _read
    return parser.read(nrows)
  File "/Users/.../LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1047, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/Users/.../LinkedIn-Easy-Apply-Bot/venv/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 224, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 801, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 857, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1925, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 69, saw 3

**Comment by zulham724** [comment]
any update, i got this error too

**Comment by dorissssy** [comment]
> any update, i got this error too

add these code to the read csv line: 
 if self.qa_file.is_file():
            try:
                df = pd.read_csv('qa.csv', on_bad_lines='skip', quotechar='"')
            except pd.errors.ParserError as e:
                print(f"Error reading CSV file: {e}")
