### ISSUE TITLE
Chrome Crashes 

### ISSUE THREAD

**Issue by EdwardOak** [nicolomantini/LinkedIn-Easy-Apply-Bot#84]
====== WebDriver manager ======
Current google-chrome version is 89.0.4389
Get LATEST driver version for 89.0.4389
There is no [linux64] chromedriver for browser 89.0.4389 in cache
Get LATEST driver version for 89.0.4389
Trying to download new driver from https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_linux64.zip
Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/89.0.4389.23]
Traceback (most recent call last):
  File "easyapplybot.py", line 22, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install())
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  
  Any idea how to troubleshoot? (Sent from Chrome on Ubuntu 18 with XCFE)

**Comment by EdwardOak** [comment]
I made sure to install latest. 

Same error.

**Comment by EdwardOak** [comment]
Upon reboot, chrome does not crash. 

New issue on Line 4 Col 10 of config.yaml

"yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yaml", line 4, column 10"

**Comment by EdwardOak** [comment]
positions**:**
