### ISSUE TITLE
Code Stops after logging in

### ISSUE THREAD

**Issue by almonteluis** [nicolomantini/LinkedIn-Easy-Apply-Bot#97]
**Describe the bug**
The bot stops running after logging in successfully. I got this message after the bot stopped.
`Traceback (most recent call last):
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 453, in <module>
    bot.start_apply(positions, locations)
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 122, in start_apply
    self.fill_data()
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 117, in fill_data
    self.browser.set_window_size(0, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1387, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1469, in set_window_rect
    raise InvalidArgumentException("x and y or height and width need values")
selenium.common.exceptions.InvalidArgumentException: Message: x and y or height and width need values`

**Error Statement**
`Traceback (most recent call last):
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 453, in <module>
    bot.start_apply(positions, locations)
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 122, in start_apply
    self.fill_data()
  File "/Users/imedia/Downloads/other/LinkedIn-Easy-Apply-Bot-master/easyapplybot.py", line 117, in fill_data
    self.browser.set_window_size(0, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1387, in set_window_size
    self.set_window_rect(width=int(width), height=int(height))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 1469, in set_window_rect
    raise InvalidArgumentException("x and y or height and width need values")
selenium.common.exceptions.InvalidArgumentException: Message: x and y or height and width need values`

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.7
 - Browser Chrome
 - Version: 102.0.5005.115 (Official Build) (x86_64)

**To Reproduce**
1. Go to easy-apply folder
2. Then run the command to start the bot
3. Wait till it logs in
4. See error in your terminal

**Expected behavior**
After log in, go to the jobs page and start applying to positions.

**Comment by fernando-granco** [comment]
Change set_window_size(0, 0) to set_window_size(1, 1) and set_window_position(0, 0) to set_window_position(1, 1).
